### ISSUE TITLE
Commands to add for OI Wiki test

### ISSUE THREAD

**Issue by Myriad-Dreamin** [OrangeX4/mitex#18]
Scanned by script
+ [x] `\notag`
+ [x] `\brack`
+ [x] `\triangle`
+ [x] `\impliedby`
+ [x] `\LaTeX`
+ [x] `\space`
+ [x] `\lnot`
+ [x] `\mathop`
+ [x] `\vert`
+ [x] `\middle`
+ [x] `\lvert`
+ [x] `\rvert`
+ [x] `\lVert`
+ [x] `\Bbb`
+ [x] `\implies`
+ [x] `\boxed`
+ [x] `\checkmark`
+ [x] `\substack`
+ [x] `\dotsb`
+ [x] `\dbinom`
+ [x] `\*`
+ [x] `\wedge`
+ [x] `\subsetneqq`
+ [x] `\emptyset`
+ [x] `\pod`
+ [x] `\lor`
+ [x] `\cr`
+ [x] `\tag`
+ [ ] `\varphi*`
+ [x] `\brace`
+ [x] `\begin{alignedat}`

**Comment by Enter-tainer** [comment]
https://katex.org/docs/support_table There is also a support table in katex. Hope that helps

**Comment by Myriad-Dreamin** [comment]
> https://katex.org/docs/support_table There is also a support table in katex. Hope that helps

We have been aware of that, but there are too many commands and feel boring on binding them all. We may only bind some commonly used commands and oiwiki used commands in first release. @OrangeX4 

All rest commands will be added in later versions.

**Comment by Enter-tainer** [comment]
Yes, I see there are a lot of weird things on that page. 🤣

**Comment by Myriad-Dreamin** [comment]
`\varphi*` is fixed by #31
