### ISSUE TITLE
`[ ,dots.down ]` is identified as content in typst

### ISSUE THREAD

**Issue by Myriad-Dreamin** [OrangeX4/mitex#24]
https://github.com/OrangeX4/mitex/blob/996f9e2fab1af7fdb9823d382dc9908a24d5a507/crates/mitex/src/lib.rs#L697-L700

**Comment by OrangeX4** [comment]
This could be a bug in typst, with minimal reproducibility like this:

```typst
$mat(; ,x)$
// Err: expected array, found content
```

Specific reasons:

```typst
#let mymat = (..args) => repr(args)
$mymat(; ,x)$
// Output: (([],), [], ([x],))
// Expected: (([],), ([], [x]))
```

I'll try to output `pmatrix(zws; zws,x)` to avoid this bug.
