### ISSUE TITLE
Things in `aligned` environment becomse inline style

### ISSUE THREAD

**Issue by Enter-tainer** [OrangeX4/mitex#45]
![image](https://github.com/OrangeX4/mitex/assets/25521218/bd5c09a8-b5d5-4887-9bf7-e4c553d0afb6)

```
#mitex(`
\begin{aligned}
\int_0^\infty x^2 dx
\end{aligned}
\\
\int_0^\infty x^2 dx
`)
```

**Comment by Myriad-Dreamin** [comment]
aligned may add a display by default. Here is the output of katex

```tex
\textstyle
\begin{aligned}
\textstyle
\int_0^\infty x^2 dx
\end{aligned}
\\
\begin{aligned}
\int_0^\infty x^2 dx
\end{aligned}
\\
\int_0^\infty x^2 dx
```

![image](https://github.com/OrangeX4/mitex/assets/35292584/0edc08e8-959b-43ce-ad86-761e7305b8b5)
