### ISSUE TITLE
`\Big` braces looks weird

### ISSUE THREAD

**Issue by Enter-tainer** [OrangeX4/mitex#47]
![image](https://github.com/OrangeX4/mitex/assets/25521218/e7746b91-5336-482c-b469-0485bf76f3e1)

```
#mitex(`
\Big\{123
`)

```

**Comment by Enter-tainer** [comment]
try this for braces/brackets/...

```
$lr(size: #180%, \{)123$
```
![image](https://github.com/OrangeX4/mitex/assets/25521218/967da528-8d45-4887-ad31-ff1e883082ac)

**Comment by Enter-tainer** [comment]
this works well for very large brace

![image](https://github.com/OrangeX4/mitex/assets/25521218/7f72b10f-4615-4685-a5f6-eaec00c03845)

**Comment by OrangeX4** [comment]
I'd also like to be able to use the `lr` function, but our current handling of the `\Big` command is as a single-parameter function, and switching to something like `\left` and `\right` requires a lot of effort.

**Comment by Enter-tainer** [comment]
idk the impl details. imo `\Big[xxx \big]` should become `lr(scale: ...%, [) xxx lr(scale: ..., ])`

**Comment by OrangeX4** [comment]
Oh, that sounds good, I'll give it a try!
